version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ../imagenes
        target: /usr/share/nginx/html/imagenes
      - type: bind
        source: ./html/index.html
        target: /usr/share/nginx/html/index.html