FROM node:latest as build-app-1
WORKDIR /app
COPY ./app/package*.json ./
RUN npm install
COPY ./app .
RUN npm run build

FROM node:latest as build-app-2
WORKDIR /app
COPY ./app/package*.json ./
RUN npm install
COPY ./app .
RUN npm run build


FROM nginx as production-stage
RUN mkdir /app
RUN mkdir /app2
COPY --from=build-app-1 /app/dist /app
COPY --from=build-app-2 /app/dist /app2
COPY nginx.conf /etc/nginx/nginx.conf
