version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - type: bind
        source: ./html
        target: /usr/share/nginx/html